### PR TITLE
fix: delete workspace from local storage on leave

### LINKED ISSUE #229: Frontend - Workspaces List error message on leave
When a user leaves a workspace that is **SELECTED** a lot of error messages are being triggered (image).
My guess is that the request to fetch pieces repositories and other data from the workspace still being fired even after the deletion of this resource.

image

### PR DESCRIPTION
**Pull request by tdari**
Fix #229

The problem was that we were not updating the workspace state to null and clearing local storage, as we do in the delete operation. When leaving the workspace, I deleted the workspace from local storage and set the workspace state to null, similar to the workspace delete operation we currently have. Additionally, I removed an unnecessary import from my previous PR.

### CODE REVIEW

File: frontend/src/context/workspaces/workspaces.tsx [hunk 1]
```diff
@@ -108,6 +108,14 @@ export const WorkspacesProvider: FC<IWorkspacesProviderProps> = ({
       removeUserWorkspace({ workspaceId, userId })
         .then(() => {
           toast.success(`User removed successfully from workspace.`);
+          const storageWorkspace = JSON.parse(
+            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+            localStorage.getItem("workspace")!,
+          );
```
Comment (vinicvaz) [inline frontend/src/context/workspaces/workspaces.tsx:114]: Can we remove the eslint disable workaround? Its preferred to not have it.
```suggestion
          const storageWorkspace = JSON.parse(
            localStorage.getItem("workspace") ?? "{}",
          );
```

**Review by vinicvaz — APPROVED** [review]
Great @tdari, thanks for submitting this!

File: frontend/src/context/workspaces/workspaces.tsx (hunk 1 above)
Comment (tdari) [reply frontend/src/context/workspaces/workspaces.tsx:114]: It is used in the delete operation too. I don't know if it is something necessary.
